# https://docs.cypress.io/guides/continuous-integration/github-actions#Caching-Dependencies-and-Build-Artifacts
name: Build and run Cypress tests

on: [push]

jobs:
  cypress-run:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout code from repository
        uses: actions/checkout@v2

      # Install NPM dependencies, cache them correctly and run all Cypress tests
      - name: Run Cypress E2E tests
        uses: cypress-io/github-action@v4
        with:
          # Records the run for Cypress Dashboard
          record: true
          # Build app
          build: npm run build -- --sourcemap false
          # Run web-server from build dist/ output
          start: npm run preview
          # Wait for web-server before starting tests
          wait-on: 'http://localhost:3001'
          # Custom command to start Cypress tests
          command: npm run test:e2e:ci
        env:
          CYPRESS_RECORD_KEY: ${{ secrets.CYPRESS_RECORD_KEY }}
          CYPRESS_PROJECT_ID: ${{ secrets.CYPRESS_PROJECT_ID }}
          # Pass GitHub token generated automatically by the action itself
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Print result
        run: |
          echo Cypress finished with: ${{ steps.cypress.outcome }}
          echo See results at ${{ steps.cypress.outputs.dashboardUrl }}
